### ISSUE TITLE
Work is slowly for bad internet connection

### ISSUE THREAD

**Issue by lutowolk** [samyk/evercookie#104]
Hello, this is very cool lib!

But this lib work is very slow for bad internet connections (mobile internet example). May be we have off anything option for make this faster? Can I remove some features from code evercookie for make this faster? 

Please help me!?

**Comment by samyk** [comment]
Disabling the history scanning (there's a variable around the top for it) should speed it up a bit. Happy to accept pull requests if you find other areas of speed issues.
