### ISSUE TITLE
[off-topic] previous weird error. duplicate https://github.com/samyk/evercookie/issues/138

### ISSUE THREAD

**Issue by cocoonkid** [samyk/evercookie#139]
https://github.com/samyk/evercookie/issues/138
* star this repo!! is what I meant

Apparently I am also unable to edit the other issue or leave a comment !?

Is this a github problem?

**Comment by ssokolow** [comment]
Check your ad-blocker. It's probably got a blanket block for any URL containing the word "evercookie".

(eg. I have to temporarily disable uBlock Origin to comment here.)

**Comment by cocoonkid** [comment]
oh wow. Yes indeed :-). Thanks so much!
