### ISSUE TITLE
Specify the license somewhere

### ISSUE THREAD

**Issue by NightKev** [samyk/evercookie#42]
As far as I can tell, there's no license info anywhere. Is this public domain? GPLv3? etc...

**Comment by TPS** [comment]
@samyk @NightKev "Solved" w/ https://github.com/samyk/evercookie/blob/master/LICENSE-BPL.md.

Close… FTW?

**Comment by TPS** [comment]
@SamyK Just FYI, & I'm sure, as per intention, that [BPL](https://github.com/samyk/evercookie/blob/master/LICENSE-BPL.md) confuses me completely.  Did you include that license just as a commentary on "public"-source (clearly not open-source!) software, or is there a more serious purpose?
