### ISSUE TITLE
Add ability to evercookie.rem('id');

### ISSUE THREAD

**Issue by KevBurnsJr** [samyk/evercookie#6]
Wouldn't it be nice if there were a function to remove the evercookie?
Or would you just evercookie.set('id', null); ?

**Comment by rosatof** [comment]
@KevBurnsJr What was the anwser ?

**Comment by KevBurnsJr** [comment]
@rosatof There was no answer. evercookie stains are permanent.

**Comment by rosatof** [comment]
@KevBurnsJr Ok thanks! So i guess setting the value to null is the only choice ?!
