### ISSUE TITLE
evercookie_indexdb_storage

### ISSUE THREAD

**Issue by danielschweiger** [samyk/evercookie#85]
the evercookie_indexdb_storage method is not used by default, why?

**Comment by gdmka** [comment]
I think i should step up as the maintainer of that code. Why it is not used?

**Comment by samyk** [comment]
That's odd -- I don't recall any reason for disabling this. Happy to merge an update using it

**Comment by samyk** [comment]
Thanks for the merge @gdmka! Closing this
