### ISSUE TITLE
Click to rediscover cookies see either null or undefined

### ISSUE THREAD

**Issue by andrisskutans** [samyk/evercookie#89]
At http://samy.pl/evercookie/ tried with Opera. Set cookies, then deleted all history from Opera, then closed Opera, opened again clicked on `Click to rediscover cookies` and saw either null or undefined.

**Comment by samyk** [comment]
Test with the latest from github -- unfortunately I haven't had a chance to update the website. Also, browsers now use evercookie as a litmus test for privacy settings so if you are deleting all privacy settings from a browser, you may find evercookie has nothing to respawn.
