### ISSUE TITLE
Uncaught TypeError: Cannot read property 'embedSWF' of undefined

### ISSUE THREAD

**Issue by Angelo3** [samyk/evercookie#90]
I'm learning about how to use evercookie, so I've tried this code:

```<html>
<head>
</head>
<body>
<script type="text/javascript" src="js/evercookie.js"></script>
<script type="text/javascript" src="js/swfobject-2.2.min.js"></script>
<script>
    var ec = new evercookie(); 
    ec.get("id", function(value) { 
    if(value==""){ec.set("id", "12345");  alert("cookie set!");}
    else{alert("Cookie value is " + value); }
    }); 
</script>
</body>
```
But I'm getting "Uncaught TypeError: Cannot read property 'embedSWF' of undefined". What am I doing wrong?

**Comment by samyk** [comment]
No other errors? Are the JS's loading properly?

**Comment by Angelo3** [comment]
No other errors on chrome; on tor browser I'm getting "
TypeError: swfobject is undefined evercookie.js:38
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. evercookie
InvalidStateError evercookie.js:43
no element found evercookie_cache.php:1"
And yes the javascript files are loaded properly

**Comment by Angelo3** [comment]
I've found out what I was doing wrong: I had to include swfobject-2.2.min.js before evercookie.js! Thanks anyway for your help :)
