### ISSUE TITLE
 Uncaught SyntaxError: Unexpected token var and Uncaught ReferenceError: evercookie is not defined

### ISSUE THREAD

**Issue by Angelo3** [samyk/evercookie#91]
I was using the same code I wrote some days ago:

```
<head>
</head>
<body>
<script type="text/javascript" src="js/swfobject-2.2.min.js"></script>
<script type="text/javascript" src="js/evercookie.js"></script>
<script>
    var ec = new evercookie(); 
    ec.get("test", function(value) { 
    if(value==undefined){ec.set("id", "12345");  alert("cookie set!");}
    else{alert("Cookie value is " + value); }
    }); 
</script>
</body>
```

But now I'm sunddenly getting
 Uncaught SyntaxError: Unexpected token var (evercookie.js:1) and Uncaught ReferenceError: evercookie is not defined (line 7).
What could be the problem?

**Comment by samyk** [comment]
Maybe evercookie.js was accidentally modified? What's in the first line on evercookie.js?

**Comment by Angelo3** [comment]
I've already tried to reupload it, but it didn't work
In the first line there's
```
try{(function(window){'use strict';var document=window.document,Image=window.Image,globalStorage=window.globalStorage,var swfobject=window.swfobject;try{var localStore=window.localStorage}catch(ex){}
```

**Comment by samyk** [comment]
I would try an unminified version first.

**Comment by Angelo3** [comment]
I've deactivated the auto-minification of the code in cloudflare, now I'm told that the error is on line 74:
   var  swfobject = window.swfobject;

**Comment by samyk** [comment]
Is the swfobject js actually getting loaded?

**Comment by Angelo3** [comment]
It isn't, but I can't figure out why

**Comment by 2014144948** [comment]
什么意思？？？
