### ISSUE TITLE
ReferenceError: evercookie is not defined

### ISSUE THREAD

**Issue by matiasleibovich** [samyk/evercookie#98]
hi. I'm having a problem. I'm getting the following error message:

ReferenceError: evercookie is not defined
	var ec = new evercookie({

this is happening on my Firefox browser, because on Chrome, it work's just fine. I couldn't find why this is happening yet. I just downloaded it and I'm trying to test it. I did not modified any file. On one browser it's working just fine, and with the other I get the script error message.

any ideas why? thanks!

**Comment by thegitty** [comment]
Try 
`var ec = new Evercookie(); // with a capital E`

**Comment by samyk** [comment]
Any luck? Closing this but reopen if still having issues.
